### ISSUE TITLE
exception: Undefined index type at AmoHook.php:79

### ISSUE THREAD

**Issue by ArtyomGitGit** [opravdin/amohook#1]
Привет)

В логах заметил exception:
Undefined index: type {"exception":"[object] (ErrorException(code: 0): Undefined index: type at vendor/opravdin/amohook/src/AmoHook.php:79)

stacktrace:
#0 vendor/opravdin/amohook/src/AmoHook.php(79): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '...', 79, Array)
#1 vendor/opravdin/amohook/src/AmoHook.php(98): Opravdin\\AmoHook\\AmoHook->get()
#2 app/Http/Controllers/API/AmoHookController.php(152): Opravdin\\AmoHook\\AmoHook->handle()

Возможно, не хватает проверки на isset($event['type'])

**Comment by opravdin** [comment]
Привет! Если не сложно -- сделай пожалуйста PR и добавь тест кейс на такой сценарий
